baseURL = "https://arranshort.xyz/"
disablePathToLower = true
languageCode = "en-us"
title = "The Adventures of Arran Short"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
